# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SmallWater Blog
brief-intro: You and me
header-img: assets/img/bike.jpg
description: "You and Me"
baseurl: "" # the subpath of your site, e.g. /blog
keyword: "quronghui, Hardware, Markdown"
url: "https://quronghui.github.io" # the base hostname & protocol for your site
github_repo: "https://github.com/quronghui/quronghui.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "love you"
sidebar-avatar:                         # use absolute URL, seeing it's used 

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: 
github_username:  quronghui
email: quronghui@hust.edu.cn
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:

description_footer: Welcome to quronghui blog

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
# duoshuo_shortname: xyao #hygblog
# disqus_shortname: #gaohaoyang
# using Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: #52bbb620d9680fd85254                            #生成的clientID
  clientSecret: # d92cec378527800b0816d1bdd26dc71eb5dd0ccd    #生成的clientSecret
  repo: quronghui.github.io    #仓库名称
  owner: quronghui    #github用户名
  admin: quronghui
  distractionFreeMode: true #是否启用类似FB的阴影遮罩

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
# baidu_tongji_id: 1cc1fc4b4b456bf7c99ce80aec5bf009
google_analytics_id:  # google 分析追踪id
ga_domain: auto

friends: [
    {
        title: "",
        href: ""
    }
]

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
# 怎么才能限制博客文章的长度，不全部显示
plugins: [jekyll-paginate]
# permalink: pretty
paginate: 5
# per_page: 5         # 每页文章数量
port: 4001

# 加了这个，本地运行会报错
# theme: jekyll-theme-slate